### PR TITLE
Fix #55 add missing types field

### LINKED ISSUE #55: updating 1.2.2 to version 2.1.1 is giving a could not find declaration file for module /@angularclass/hmr'
Updating my dependencies I came across this error when updating from 1.2.2 to v 2.1.1 produces this error 

[at-loader] ./src/app/app.module.ts:7:69 
    TS7016: Could not find a declaration file for module '@angularclass/hmr'. '/xxx/xxx/xxx/node_modules/@angularclass/hmr/dist/index.js' implicitly has an 'any' type.

### PR DESCRIPTION
**Pull request by vilic**
#55

### CODE REVIEW

**Comment by jibbers42** [comment]
I have the same issue, the PR works for me.

**Comment by jerome-quere** [comment]
I have the same issue, the PR works for me.

**Comment by xtianus79** [comment]
are they going to merge this in anytime soon?

**Comment by guilhermevrs** [comment]
Also interested in it

**Comment by atbe** [comment]
Would very much like to see this merged in, it solved my compilation issue as well (because the types were not resolved by AOT). Thanks!

**Comment by jibbers42** [comment]
@gdi2290 Is there something about this PR that you don't like? It resolves an issue for several people and yet it was ignored in the release made yesterday.

**Comment by gdi2290** [comment]
thanks, released as @angularclass/hmr@2.1.3

**Pull request merged**
